### ISSUE TITLE
Save button on edit profile is not working properly

### ISSUE THREAD

**Issue by iulitaalpetri** [vlandero/Share-Location#19]
When i modify something on my profile in the Profile fragment and i try to click on save button, it does not update and i get an error. Weird is that sometimes it worked, but I cannot reproduce the error. Please check the save button functionality in the Profile fragment.

**Comment by radugheo** [comment]
I'll look into it.

**Comment by vlandero** [comment]
Coult not reproduce the bug. Reopen if you can attach a screenshot with the bug.
